### ISSUE TITLE
panic: time: missing Location in call to Date

### ISSUE THREAD

**Issue by ekle** [luxifer/ical#3]
hi, 
i got a panic on http://rpayc.com.au/news-events/event-calendar-list?format=raw&type=ical

panic: time: missing Location in call to Date

goroutine 26 [running]:
time.Date(0x7e2, 0x8, 0x16, 0xe, 0x0, 0x0, 0x0, 0x0, 0xc8f1, 0x15, ...)
        /opt/go1.10.2/src/time/time.go:1313 +0x659
time.parse(0x6da4da, 0xf, 0xc420238759, 0xf, 0x0, 0x0, 0x4, 0x0, 0x70ce60, 0xc420096e50, ...)
        /opt/go1.10.2/src/time/format.go:1094 +0x2ab8
time.ParseInLocation(0x6da4da, 0xf, 0xc420238759, 0xf, 0x0, 0x1, 0xed307259e, 0x854460, 0xc420069320, 0xc420069320)
        /opt/go1.10.2/src/time/format.go:783 +0x62
github.com/luxifer/ical.parseDate(0xc4200997d0, 0x854460, 0x6d93a6, 0xb, 0xc4200693b8, 0x0, 0x0)
        /home/andreas/go/src/github.com/luxifer/ical/parse.go:523 +0x10e
github.com/luxifer/ical.(*parser).validateEvent(0xc420249980, 0xc4200e02c0, 0xc4201ce000, 0x4)
        /home/andreas/go/src/github.com/luxifer/ical/parse.go:426 +0x723
github.com/luxifer/ical.(*parser).scanDelimiter(0xc420249980, 0xf, 0x229, 0xc420238829, 0xa, 0xc4200a6480, 0x4)
        /home/andreas/go/src/github.com/luxifer/ical/parse.go:227 +0x76
github.com/luxifer/ical.(*parser).scanContentLine(0xc420249980, 0x0, 0x0)
        /home/andreas/go/src/github.com/luxifer/ical/parse.go:276 +0x9b6
github.com/luxifer/ical.(*parser).parse(0xc420249980, 0x25ce, 0xc4200a6440, 0x25ce)
        /home/andreas/go/src/github.com/luxifer/ical/parse.go:193 +0xd2
github.com/luxifer/ical.Parse(0x70d320, 0xc42011e5c0, 0x0, 0x4, 0xc4201ee800, 0x26d9)
        /home/andreas/go/src/github.com/luxifer/ical/parse.go:85 +0x1f6
main.parse(0xc4201ec000, 0x26db, 0x26db, 0x3e00, 0xc4201ec000, 0x26db, 0x0)
        /home/andreas/t/crawler.go:182 +0x131
main.handle(0x688d, 0xc4200200a0, 0x48)
        /home/andreas/t/crawler.go:99 +0x47a
main.main.func1()
        /home/andreas/t/crawler.go:45 +0x9c
created by main.main
        /home/andreas/t/crawler.go:56 +0x19e
exit status 2

**Comment by luxifer** [comment]
Hi,

Thanks for reporting. I'm sorry but I introduced a BC break in the
ical.Parse method. You have to pass nil as a second parameter.

I'm really sorry but at the time when I added this parameter I did not
think enough about the consequences.

Regards

Florent Viel

Le jeu. 16 août 2018 à 12:03, Andreas Jaekle <notifications@github.com> a
écrit :

**Comment by minglecm** [comment]
I think this might be a different issue.  Looking at the ICS file, `TZID=Z` which isn't recognized as a valid time zone.

`time.LoadLocation("Z")` returns nil and then `time.ParseInLocation` will panic.

Reproduction: https://play.golang.org/p/L4i7wsZh2kF

Looking at the [iCalendar spec](https://www.kanzaki.com/docs/ical/dateTime.html), I don't think this is a properly formatted calendar file.

> The date with UTC time, or absolute time, is identified by a LATIN CAPITAL LETTER Z suffix character (US-ASCII decimal 90), the UTC designator, appended to the time value.

> The TZID property parameter MUST NOT be applied to DATE-TIME properties whose time values are specified in UTC.

**Comment by luxifer** [comment]
Thanks for the reproducible playground. I'll have a look on Monday to fix
this edge case. If TZID=Z we should not try to load the Z timezone but load
the UTC.

Florent Viel

Le ven. 17 août 2018 à 19:37, Caleb Mingle <notifications@github.com> a
écrit :
